### ISSUE TITLE
question regarding configuration

### ISSUE THREAD

**Issue by steuerzentrale** [MariusLang/node-red-contrib-feiertage-switzerland#8] opened 2022-06-06 17:14 UTC
Hi there

First of all many thanks for this nice add-on, this helps to take my automations to the next level! I installed the palette via Node-RED running on Home Assistant OS 8.1 on a Raspi Pi 4.

Today is a holiday (Pfingstmontag) which is also represented in the add-on. If I inject a msg.payload with the keyword **isTodayHoliday** it should output **true** but it says false.
<img width="1074" alt="Bildschirmfoto 2022-06-06 um 18 59 14" src="https://user-images.githubusercontent.com/75168550/172211338-b4702157-1ae4-408e-adf6-989b4f016425.png">

I read the information on the add-on and it says that the timezone as well as location must be set correctly.
<img width="593" alt="Bildschirmfoto 2022-06-06 um 18 57 30" src="https://user-images.githubusercontent.com/75168550/172211238-77579c35-80ec-4228-a079-be8fc7e7e5ba.png">

location configuration in the config.yaml-file
<img width="287" alt="Bildschirmfoto 2022-06-06 um 19 15 51" src="https://user-images.githubusercontent.com/75168550/172211599-f17debde-584a-4382-a351-ca88b578166d.png">

I would be glad if you could help me to sort out the issue or may explain if I misconfigured something wrong.

Regards from Switzerland ;)

Andrew

**Comment by MariusLang** [comment] 2022-06-06 19:21
Dear Andrew,
thanks for using node-red-contrib-feiertage-switzerland and reporting this issue 🥳

The issue you mentioned is caused by a bug in the code.
So don't worry, it isn't your fault.

The fix is going to be implemented in the upcoming version of node-red-contrib-feiertage-switzerland.
I'm planning to release this version tomorrow.

Enjoy the last hours of Pfingstmontag 😉
Best Regards Marius

**Comment by steuerzentrale** [comment] 2022-06-06 20:25
Hi Marius

many thanks for the quick reply, thats great news. I may use this thread to give feedback on two points:

I would appreciate if the exact date of the holiday e.g Josefstag **19.03.2022** is being displayed after the holiday istelf.

<img width="301" alt="Bildschirmfoto 2022-06-06 um 22 23 05" src="https://user-images.githubusercontent.com/75168550/172242382-6906cfc2-2d63-4e5f-9ae4-4c0ba3e662f4.png">

I also found a holiday called true. what is its purpose?

<img width="297" alt="Bildschirmfoto 2022-06-06 um 22 24 53" src="https://user-images.githubusercontent.com/75168550/172242647-27fa125a-8f6a-4959-9d01-e95382a50521.png">

**Comment by MariusLang** [comment] 2022-06-07 09:14
Hi Andrew,

thanks for your enhancements 👍

Of course **true** isn't a holiday 😉
Here something went wrong. This holiday should be named **Peter und Paul**.
Also this bug will be fixed in the upcoming version.

Displaying the holiday's date after its name is currently difficult to implement.
Therefore the whole node structure has to be changed.
It's definitely on my To-Do List for a new major version.

If you have more enhancements into your mind or you find more bugs in the future, feel free to open a new issue.

Best Regards from Germany
Marius

**Comment by MariusLang** [comment] 2022-06-09 09:31
Dear Andrew,

the new version _1.4.3_ fixes the issue you mentioned.
You can easily upgrade the node in NodeRed to **node-red-contrib-feiertage-switzerland@1.4.3**.

Thanks for reporting this issue 👍

Best Regards Marius

**Closed as completed by MariusLang** 2022-06-09 09:31 UTC
Labels: bug, enhancement
